spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest

rocketmq:
  name-server: localhost:9876
  producer:
    group: spring-boot-group
    retry-times-when-send-failed: 10
    send-message-timeout: 10000
