spring:
  rabbitmq:
    host: 123.57.107.76
    port: 8001
    virtual-host: /test
    username: guest
    password: guest

rocketmq:
  name-server: 192.168.232.10:9876
  producer:
    group: spring-boot-group
    retry-times-when-send-failed: 10
    send-message-timeout: 10000
