server:
  port: 8888
spring:
  application:
    name: spring-cloud-gateway

  profiles:
    active: filters
  # 配置 nacos 注册中心地址
  cloud:
    nacos:
      discovery.server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          # 默认为false，设为true开启通过微服务创建路由的功能，即可以通过微服务名访问服务
          # http://localhost:8888/spring-cloud-user/user/findOrderByUserId/1
          enabled: true
      # 是否开启网关
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION

