server:
  port: 8082
#  servlet:
#    context-path: /spring-cloud-order

spring:
# 解决 2.6.x swagger 报错，SpringBoot 由 AntPathMatcher 变为 PathPatternMatcher

  application:
    name: spring-cloud-order  #微服务名称
  cloud.nacos.discovery:
      server-addr: 127.0.0.1:8848
      #group:  mall-order
      #cluster-name: SH
      #ephemeral: false
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    compatibility-verifier:
      enabled: false
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        flow-rules:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP   # 注意groupId对应Sentinel Dashboard中的定义
            data-type: json
            rule-type: flow
        degrade-rules:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: degrade
        param-flow-rules:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: param-flow
        authority-rules:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: authority
        system-rules:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: system

#mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.spring.cloud.order.entity


#暴露actuator端点   http://localhost:8020/actuator/sentinel
management.endpoints.web.exposure.include: '*'

#true开启sentinel对resttemplate的支持，false则关闭  默认true
resttemplate:
  sentinel:
    enabled: true

hmily:
  ribbon:
    rule:
      enabled: true

ribbon:
  MaxAutoRetriesNextServer : 0
  MaxAutoRetries: 0

feign:
  sentinel:
    enabled: true  #开启sentinel对feign的支持 默认false
