
spring:
  shardingsphere:
    datasource:
      # 多数据源
      names: test0,test1
      test1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.208.128:3306/sharding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
      test0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.208.128:3306/sharding1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
    sharding:
      tables:
        course: # course 表
          # test1 或者 test2 库,course1course2 表
          actual-data-nodes: test$->{0..1}.course_$->{0..1}
          # 主键生成策略
          key-generator:
            column: id
            type: SNOWFLAKE
            props.worker.id: 1
          # 分表策略
          table-strategy.standard:
            sharding-column: user_id
            precise-algorithm-class-name: com.roy.sharding.algorithm.standard.MyPreciseTableShardingAlgorithm
            range-algorithm-class-name: com.roy.sharding.algorithm.standard.MyRangeTableShardingAlgorithm
          # 分库策略
          database-strategy.standard:
            sharding-column: id
            precise-algorithm-class-name: com.roy.sharding.algorithm.standard.MyPreciseDSShardingAlgorithm
            range-algorithm-class-name: com.roy.sharding.algorithm.standard.MyRangeDSShardingAlgorithm
        # 强制路由
#        table-strategy.hint:
#            algorithm-class-name: com.roy.sharding.algorithm.hint.MyHintTableShardingAlgorithm

      # 广播策略，即公共表与分库分表前无差异
      broadcast-tables: t_dict
      tables.t_dict.key-generator:
        column: dict_id
        type: SNOWFLAKE
    props.sql.show: true

  main:
    allow-bean-definition-overriding: true
