spring:
  application:
    name: elasticsearch
  elasticsearch.rest.uris: localhost:9200
  profiles:
    active: default
  cloud:
    zookeeper.discovery.root: default

server:
  servlet:
    context-path: /elasticsearch

logging:
  config: classpath:logback-spring.xml
  logstash.host: localhost:4560
  level:
    com.summary.elasticsearch.config: debug
    org.springframework.data.elasticsearch.client.WIRE: trace
