dubbo:
  scan:
    # 指定 Dubbo 服务实现类的扫描基准包
    base-packages: com.spring.cloud.dubbo.provider.service
#  application:
#      name: spring-cloud-dubbo-provider-user
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
#  registry:
#    #挂载到 Spring Cloud 注册中心  高版本可选
#    address: spring-cloud://1.15.19.68:8848

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: 1.15.19.68:8848
  application:
    name: spring-cloud-dubbo-provider-user
  main:
    # Spring Boot2.1及更高的版本需要设定
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.19.68:3306/cloud?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
