server:
  port: 8080

ip:
  host: 192.168.208.128

spring:
  redis:
    database: 0
    timeout: 3000
    password: zhuge
    #    sentinel: #哨兵模式
    #      master: mymaster #主服务器所在集群名称
    #      nodes: ${ip.host}:26379, ${ip.host}:26380, ${ip.host}:26381
    cluster:
      nodes: ${ip.host}:9000,${ip.host}:9001,${ip.host}:9002,${ip.host}:9003,${ip.host}:9004,${ip.host}:9005
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000
