#垂直分表策略
spring:
  shardingsphere:
    datasource:
      names: test1,test2 # 配置真实数据源
      test1: # 配置第 1 个数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.208.128:3306/sharding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
      test2: # 配置第 1 个数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.208.128:3306/sharding1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
    sharding:
      tables:
        course:
          # 指定表的分布情况 配置表在哪个数据库里，表名是什么。水平分表，分两个表：test.course_1,test.course_2
          actual-data-nodes: test$->{1..2}.course_$->{1..2}
          # 指定表的主键生成策略
          key-generator:
            column: cid
            type: SNOWFLAKE
            props.worker.id: 1 #雪花算法的一个可选参数
          # 指定分片策略 约定cid值为偶数添加到course_1表。如果是奇数添加到course_2表。
          table-strategy.inline:
            sharding-column: userId # 根据计算的字段算出对应的表名。
            algorithm-expression: course_$->{userId%2+1}
          database-strategy.inline:
            sharding-column: cid
            algorithm-expression: test$->{cid%2+1}
#      default-database-strategy:
#        inline:
#          sharding-column: cid
#          algorithm-expression: test$->{cid % 2+1}
    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true

