server:
  port: 8010

spring:
  application:
    name: rocket-mq-consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_user?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

rocketmq:
  name-server: localhost:9876
  producer:
    group: producer_bank
